name = input("Enter your name : ")
print("Hello," + name +  " Welcome to Band Name Generator!")
city = input("Enter your City name\n")
pet = input("Enter your pet name\n")
print("Band name could be " + city + " " + pet)
